#!/bin/sh
set -eu
# pip3 freeze --path "$(poetry env info --path)/lib/python3.13/site-packages" > state/requirements-poetry.txt
pip3 freeze --path "$(scripts/poetry/run python3 -c 'import site; print(site.getsitepackages()[0])')" > state/requirements-poetry.txt
pip3 freeze --path "$(scripts/uv/run python3 -c 'import site; print(site.getsitepackages()[0])')" > state/requirements-uv.txt
diff state/requirements-poetry.txt state/requirements-uv.txt | bat -p --paging=never
rm state/requirements-poetry.txt state/requirements-uv.txt
