"""
This type stub file was generated by pyright.
"""

"""ASFQuart - Configuration readers"""
DEFAULT_CONFIG_FILENAME = ...

def static(
    func,
):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Coroutine[Any, Any, None]]:
    """Standard wrapper for a configuration parser. Reads config.yaml and passes it to the callback as a dict"""
    ...
