"""initial schema

Revision ID: 15182b58521a
Revises:
Create Date: 2025-02-11 20:09:20.011634

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "15182b58521a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
