"""initial_schema

Revision ID: 1779875a3f38
Revises:
Create Date: 2025-02-19 19:55:33.587351

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1779875a3f38"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
