"""initial_schema

Revision ID: 5d63e3dd5e93
Revises:
Create Date: 2025-02-19 20:56:26.175412

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5d63e3dd5e93"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
