"""initial_schema

Revision ID: 609dc199438f
Revises:
Create Date: 2025-02-21 20:20:02.574246

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "609dc199438f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
