"""initial_schema

Revision ID: b561e6142755
Revises:
Create Date: 2025-02-19 18:52:21.878941

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b561e6142755"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
