"""initial_schema

Revision ID: b8dd95b83501
Revises:
Create Date: 2025-02-19 20:20:11.349128

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b8dd95b83501"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
