"""initial_schema

Revision ID: d3ff8c13bb8b
Revises:
Create Date: 2025-02-20 16:49:57.374714

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d3ff8c13bb8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
