"""initial_schema

Revision ID: d8434a3de3da
Revises:
Create Date: 2025-02-20 15:24:43.391427

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d8434a3de3da"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
