#!/bin/sh
set -eu
sudo docker build -t tooling-atr-experiments --build-arg BIND=0.0.0.0:443 --build-arg VERSION="$(git log -1 --date=format:'%Y-%m-%d %H:%M' --pretty=format:'<a href=\"https://github.com/apache/tooling-atr-experiments/commit/%H\">%cd %h</a>')" -f Dockerfile.alpine .
