#!/bin/sh

if [ -d "${HOME}/tooling-trusted-release" ]
then
  MOUNT="${HOME}/tooling-trusted-release/state"
else
  MOUNT="./state"
fi

docker run --rm -d -v "${MOUNT}:/opt/atr/state" --network host --name tooling-trusted-release tooling-trusted-release
