#!/bin/sh

if [ -d "${HOME}/tooling-trusted-release" ]
then
  MOUNT="${HOME}/tooling-trusted-release/state"
else
  MOUNT="./state"
fi

BIND="${BIND:=127.0.0.1:8080}"

docker run --rm -d -v "${MOUNT}:/opt/atr/state" -e BIND="${BIND}" --network host --name tooling-trusted-release tooling-trusted-release
